version: '3.7'

services:
  db:
    container_name: db
    image: mariadb:10.4
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USERNAME: bagas
      MARIADB_PASSWORD: 1234
    ports:
      - 3306:3306

  go_services:
    container_name: go_services
    build: ./backend
    ports: 
      - 8080:8080
    restart: always
    env_file: "/backend/.env.local"
    # volumes:
    networks:
      - go_services
    depends_on:
      - db
        
        
    

# volumes:
#   mysql_data:
  # go_services:

networks:
  go_services:
    driver: bridge
  db: 
    driver: bridge