version: '3.7'

services:
  db:
    container_name: db
    image: mariadb:10.11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USERNAME: banturiset
      MARIADB_PASSWORD: 1234
    ports:
      - 3306:3306
   

  app:
    container_name: app
    build: ./backend
    ports: 
      - 8080:8080
    restart: always
    env_file: "/backend/.env.local"
    # volumes:
   
    depends_on:
      - db
        
        
    

# volumes:
#   mysql_data:
  # banturiset:

